### PR TITLE
Add a proposed work item for JSON Web Proof spec incubation

### PR DESCRIPTION
**Pull request by quartzjer**

### CODE REVIEW

**Comment by dwaite** [comment]
I accept being a co-owner

**Comment by wyc** [comment]
Interested in contributing a Rust implementation as an extension to our [`ssi`](https://github.com/spruceid/ssi) library, possibly piecing out into a separate library. Will decide degree of commitment to this after there is some more definition around data models & protocols.

Also interested in how the owners see relationships between this work item and draft spec here:
https://datatracker.ietf.org/doc/html/draft-jordan-jws-ct

**Comment by quartzjer** [comment]
> Also interested in how the owners see relationships between this work item and draft spec here:
> https://datatracker.ietf.org/doc/html/draft-jordan-jws-ct

@wyc Aware of the CT work, the focus of JWP doesn't overlap (that I'm aware), as the goals are specifically selective disclosure and unlinkability using ZKPs.  If you think maybe there is some overlap though, or have any other questions please feel free to jump on the issue tracker here: https://github.com/json-web-proofs/json-web-proofs/issues

**Comment by OR13** [comment]
Related https://github.com/w3c-ccg/community/issues/204

**Pull request merged**
