### PR TITLE
modifying the policy as code work item to reflect a focus on verifiab…

### PR DESCRIPTION
**Pull request by dhuseby**
…le computation. There is currently no solution for a high level policy-as-code language designed for translation to R1CS gadgets with support for both trusted setups (zkSNARKS) and untrusted setups (Bulletproofs). 

Signed-off-by: Dave Huseby <dave@cryptid.tech>

### CODE REVIEW

**Comment by dhuseby** [comment]
I'm hoping Wayne will review and approve this.

**Comment by wyc** [comment]
If we limit the scope to languages that can compile to arithmetic circuits, wouldn't this disallow injecting external data sources in the course of running the code and also computations that can't be expressed as arithmetic circuits? We will need to poll external data sources for our policy-as-code permissioning system.

You could maybe specify a preamble to load those data into variables as inputs into the circuit, but sometimes branching execution would be preferred for efficient execution. Maybe we can allow designation of subsections of the code as representable as arithmetic circuits instead? I think it's a tough requirement that all policy must boil down to circuits, and requiring verifiable computations for everything is a very tall order.

**Comment by dhuseby** [comment]
@wyc you make good points. I like the idea of a preamble stage that gathers the inputs. So AFAIK, we originally talked about being non-Turing complete so that all policies are bounded computations. It turns out that all bounded computations can be converted to R1CS gadgets and thus can run as verified computations. So as I see it, if we keep the bounded computation requirement then it keeps support for verified computation but doesn't mandate it. If you agree I'll modify this PR to reflect that. I think you're right that doing _everyting_ as a verified computation is a tall order but that is required for our primary use case: [Qualifications](https://dwhuseby.medium.com/zero-architecture-is-the-way-forward-5a0080925c76?source=friends_link&sk=c6c64d124bbc1361a0bbc24ffa283951).

**Comment by dhuseby** [comment]
@wyc need to get together and mash our requirements together and get this PR cleaned up and merged.

**Comment by brentzundel** [comment]
As discussed in 26 May meeting, we are closing this PR as stale.

**Pull request closed without merging**
